export const liveFeedMessages = [
  'Stakeholder alignment pending review.',
  'Operational monitoring continues without interruption.',
  'Draft framework for interim framework initiated.',
  'Monitoring intensity remains at projected levels.',
  'Cross-directorate consultation in progress.',
  'Preliminary assessment of preliminary findings underway.',
  'Strategic oversight committee convenes next quarter.',
  'Documentation phase entering documentation phase.',
  'Awaiting translation of previous translation.',
  'Working group establishes subworking group.',
  'Concern levels monitored by monitoring division.',
  'Implementation timeline for timeline under review.',
  'Stakeholder feedback on feedback mechanism received.',
  'Situation remains under active observation.',
  'Monitoring protocols updated to reflect monitoring needs.',
  'Administrative alignment proceeding administratively.',
]

export const committeeTemplates = {
  prefixes: [
    'Subcommittee on',
    'Working Group for',
    'Committee for',
    'Task Force on',
    'Advisory Panel on',
    'Steering Group for',
    'Joint Commission on',
  ],
  subjects: [
    'Temporal Stakeholder Alignment',
    'Interim Monitoring Protocols',
    'Cross-Border Cheese Labeling',
    'Strategic Banana Resilience',
    'Administrative Framework Harmonization',
    'Procedural Compliance Oversight',
    'Sustainability Impact Assessment',
    'Digital Transformation Monitoring',
    'Regulatory Coherence Analysis',
    'Stakeholder Engagement Methodology',
    'Implementation Timeline Development',
    'Documentation Standards Review',
    'Inter-Agency Coordination',
    'Risk Assessment Framework',
    'Transparency Mechanism Design',
    'Bureaucratic Process Optimization',
    'Consultation Procedure Reform',
    'Policy Instrument Calibration',
    'Monitoring System Evaluation',
    'Strategic Direction Setting',
  ],
  statuses: [
    'In consultation',
    'Awaiting translation',
    'Under review',
    'Deferred',
    'Pending approval',
    'In drafting phase',
  ],
  cadences: ['Weekly', 'Bi-weekly', 'Monthly', 'Quarterly'],
}

export const directorates = [
  'DG ADMIN',
  'DG MONITOR',
  'DG CONSULT',
  'DG OVERSIGHT',
  'DG FRAMEWORK',
  'DG COMPLIANCE',
]
