import { Info, Shield, AlertCircle } from 'lucide-react'

export default function About() {
  return (
    <section id="about" className="ops-panel">
      <div className="flex items-center space-x-3 mb-6">
        <Info className="text-ops-green" size={28} />
        <div>
          <h2 className="text-2xl font-mono font-bold text-ops-green">
            ABOUT THIS OPERATION
          </h2>
          <p className="text-gray-400 text-sm">Mission parameters and disclaimers</p>
        </div>
      </div>

      <div className="space-y-6">
        {/* Mission statement */}
        <div className="bg-ops-dark border border-ops-border rounded-lg p-6">
          <div className="flex items-start space-x-3">
            <Shield className="text-ops-green mt-1 flex-shrink-0" size={20} />
            <div>
              <h3 className="text-sm font-mono font-bold text-ops-green mb-2">
                MISSION STATEMENT
              </h3>
              <p className="text-sm text-gray-300 leading-relaxed">
                This monitoring installation is dedicated to the continuous observation
                of situations. Our core mandate encompasses the identification,
                documentation, and sustained observation of developments across all
                relevant domains. We maintain comprehensive awareness through
                systematic monitoring protocols while ensuring appropriate levels of
                concern are maintained at all times.
              </p>
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="bg-ops-dark border border-ops-amber rounded-lg p-6">
          <div className="flex items-start space-x-3">
            <AlertCircle className="text-ops-amber mt-1 flex-shrink-0" size={20} />
            <div>
              <h3 className="text-sm font-mono font-bold text-ops-amber mb-2">
                OPERATIONAL DISCLAIMER
              </h3>
              <div className="text-sm text-gray-300 leading-relaxed space-y-3">
                <p>
                  <strong>This site is parody.</strong> It is a satirical commentary on
                  bureaucratic processes and institutional monitoring culture. No
                  affiliation with any governmental or intergovernmental institution is
                  implied or intended.
                </p>
                <p>
                  All content generated by this system is fictional and intended for
                  entertainment purposes. Any resemblance to actual statements,
                  committees, or monitoring operations is purely coincidental and part
                  of the satirical nature of this project.
                </p>
                <p>
                  This project does not target, mock, or represent any specific
                  individuals, protected groups, or communities. The humor is directed
                  solely at processes, not people.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Methodology */}
        <div className="bg-ops-dark border border-ops-border rounded-lg p-6">
          <h3 className="text-sm font-mono font-bold text-ops-green mb-3">
            MONITORING METHODOLOGY
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-gray-300">
            <div>
              <p className="text-xs font-mono text-gray-500 mb-1">PHASE 1</p>
              <p className="font-mono">Identify situation requiring monitoring</p>
            </div>
            <div>
              <p className="text-xs font-mono text-gray-500 mb-1">PHASE 2</p>
              <p className="font-mono">Monitor the identified situation</p>
            </div>
            <div>
              <p className="text-xs font-mono text-gray-500 mb-1">PHASE 3</p>
              <p className="font-mono">Continue monitoring indefinitely</p>
            </div>
          </div>
        </div>

        
      </div>
    </section>
  )
}
